### ISSUE TITLE
warning: passing argument 2 of 'kobject_init_and_add' discards 'const'

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#160]
After fb9e272f7d563fcd4b785dd744152c37b88e6298 we're getting this build warning on many kernels ranging at least from 3.10.x to 5.10.x:

```
In file included from /home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/../../../p_lkrg_main.h:380:0,
                 from /home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/p_hiding.c:18:
/home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/p_hiding.c: In function 'p_unhide_itself':
/home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/../../../modules/self-defense/hiding/p_hiding.h:73:11: warning: passing argument 2 of 'kobject_init_and_add' discards 'const' qualifier from pointer target type [enabled by default]
    struct module_use *p_use;                                               \
           ^
/home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/p_hiding.c:90:4: note: in expansion of macro 'P_UNHIDE_FROM_KOBJ'
    P_UNHIDE_FROM_KOBJ(P_SYM(p_find_me),p_tmp_kset,p_tmp_ktype);
    ^
In file included from include/linux/module.h:16:0,
                 from /home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/../../../p_lkrg_main.h:26,
                 from /home/solar/lkrg/lkrg-build/src/modules/self-defense/hiding/p_hiding.c:18:
include/linux/kobject.h:90:5: note: expected 'struct kobj_type *' but argument is of type 'const struct kobj_type *'
 int kobject_init_and_add(struct kobject *kobj,
     ^
```

@Adam-pi3 I guess you added the `const` to suppress a similar warning on assignment on some newer kernels? Ideally, we'd avoid it on all.

While at it, why does the function have this comment:

```c
void p_unhide_itself(void) {

   /* Dead function - used only during development process */
```

The function _is_ used in default builds of LKRG. Perhaps the comment is out of date, and should be dropped?

We should also fix the typo in the comment here:

```
./src/modules/comm_channel/p_comm_channel.c:         p_unhide_itself(); // Unide module!
```

**Comment by Adam-pi3** [comment]
@solardiz correct, I've added it to avoid warnings on a newer kernel compilation.
Yes, this feature (unhiding) originally was not designed to be on `production` and LKRG should be hidden (by default) after successful initialization. However, we decided to go otherwise.

**Comment by Adam-pi3** [comment]
It should be fixed by https://github.com/lkrg-org/lkrg/commit/5fededdf466d1c483e7f19659efcf0b86207dc01. @solardiz can you verify?

**Comment by solardiz** [comment]
@Adam-pi3 Thanks. The warning is gone for me (so far test-built on one system that previously had it). So I'll close this issue now.

However, the commit message also says "fixes compilation for kernels < 5.10" and makes a change to `p_arch_jump_label_transform_apply_entry`. I am puzzled by this because I didn't see any issue compiling LKRG for kernels below 5.10 a few days ago - I guess maybe a specific narrow range of kernel versions was affected, not all below 5.10. Also, I think ideally that change would have been a separate commit.

**Comment by Adam-pi3** [comment]
@solardiz `RET_INSN_OPCODE` was introduced with kernel 5.10 (not below). I'm surprised you didn't see any warnings. Do you use some distro kernels?

**Comment by solardiz** [comment]
@Adam-pi3 I think the reason is the affected code is within `#ifdef P_LKRG_CI_ARCH_JUMP_LABEL_TRANSFORM_APPLY_H`, which we define on 5.3+. So this gives us that "narrow range of kernel versions" in my guess. I didn't try kernels in the 5.3 to 5.9 range. Apparently, we don't have them in our GitHub Actions tests either.
