### ISSUE TITLE
warning: array subscript 2048 is outside array bounds of 'p_ro_page[1]'

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#185]
As seen on recent systems - e.g., the below is copied from "mkosi boot (mainline)" - but not on older ones:

```
   CC [M]  /root/src/src/p_lkrg_main.o
In file included from ./include/linux/kernel.h:29,
                 from /root/src/src/p_lkrg_main.h:24,
                 from /root/src/src/p_lkrg_main.c:18:
/root/src/src/p_lkrg_main.c: In function 'p_lkrg_register':
./include/linux/printk.h:446:44: warning: array subscript 2048 is outside array bounds of 'p_ro_page[1]' {aka 'struct _p_lkrg_ro_page[1]'} [-Warray-bounds]
  446 | #define printk(fmt, ...) printk_index_wrap(_printk, fmt, ##__VA_ARGS__)
      |                                            ^
./include/linux/printk.h:418:17: note: in definition of macro 'printk_index_wrap'
  418 |                 _p_func(_fmt, ##__VA_ARGS__);                           \
      |                 ^~~~~~~
/root/src/src/modules/print_log/p_lkrg_print_log.h:178:21: note: in expansion of macro 'printk'
  178 |       p_print_ret = printk(p_fmt, ## p_args);                                            \
      |                     ^~~~~~
/root/src/src/modules/print_log/p_lkrg_print_log.h:125:21: note: in expansion of macro 'p_print_info'
  125 |       p_print_ret = p_print_info(__P_LKRG_INFO P_LKRG_SIGNATURE p_fmt, ## p_args);       \
      |                     ^~~~~~~~~~~~
/root/src/src/p_lkrg_main.c:157:7: note: in expansion of macro 'p_print_log'
  157 |       p_print_log(P_LKRG_INFO, "*(p_long_tmp[0x%lx]+3*PAGE_SIZE) => [0x%lx] 0x%lx\n",
      |       ^~~~~~~~~~~
/root/src/src/p_lkrg_main.c:48:11: note: while referencing 'p_ro'
   48 | p_ro_page p_ro __p_lkrg_read_only = {
      |           ^~~~
```

**Comment by Adam-pi3** [comment]
We are intentionally crossing the boundary here for the debugging purposes. I'm OK fixing it and remove the last debug dump. Although, there are a few other cases where we do intentionally cross such boundaries. It looks like the newer kernel / compiler options are very strict. I wonder if we can add some kind of #pragma around a few codes where we know it is desired (e.g., reading entire RO section). @solardiz are you aware of any flags like that?

**Comment by solardiz** [comment]
> We are intentionally crossing the boundary here for the debugging purposes. I'm OK fixing it and remove the last debug dump.

I think we should remove the last one.

> there are a few other cases where we do intentionally cross such boundaries.

Where do we? If detectable by the compiler, it's free to assume undefined behavior and as an optimization do something other than what we expect, even if we were to suppress the warnings.

However, so far the above is the only such warning.
