### ISSUE TITLE
Forced into emergency mode due to "Failed to mount boot-efi.mount" error

### ISSUE THREAD

**Issue by Krish-sysadmin** [lkrg-org/lkrg#198]
Fedora 36, stock kernel: 5.18.9-200.fc36.x86_64

UEFI secure boot is enabled, LUKS encrypted. Module correctly installed, tested, signed and it loads. Grub commandline:

```
slab_nomerge init_on_alloc=1 init_on_free=1 page_alloc.shuffle=1 pti=on randomize_kstack_offset=on vsyscall=none debugfs=off module.sig_enforce=1 mce=0 loglevel=0 spectre_v2=on spec_store_bypass_disable=on ipv6.disable=1
```

With lkrg installed and enabled on Fedora 36 at boot one sees the emergency mode prompt and prior to this the error message "Failed to mount boot-efi.mount - /boot/efi". The logs show "[p_lkrg] Blocked usermodehelper execution of [/usr/sbin/modprobe]". 

In emergency mode, while LKRG is active mounting /boot/efi fails and says that vfat is not recognised and to check dmesg which outputs "Blocked usermodehelper execution of [/usr/sbin/modprobe]" again. When I unload LKRG and then attempt it again as expected it works.

After some more digging I learnt that lkrg requires kprobes and thus I disabled lockdown in "confidentiality" mode. However, the issue still remains. 

I am unable to diagnose the source of this issue, do you know how to fix this issue?

Thank you!

**Comment by Krish-sysadmin** [comment]
Update: I added the sysctl "lkrg.umh_validate=0" and that fixes the issue but that disables validation of uses of usermodehelper which is not desired. So what can be done about this? @Adam-pi3 @solardiz  pinged so that this issue gets noticed. Thank you. Apologies if pinging isn't courteous

**Comment by solardiz** [comment]
We use a hard-coded allow list of known programs invoked via UMH. It currently includes `/sbin/modprobe`, but not `/usr/sbin/modprobe`. We probably need to add the latter, but I am wondering whether the issue would also occur for other programs - did Fedora make a global change perhaps causing `/usr/sbin` paths to be used, or is this an isolated occurrence?

**Comment by Krish-sysadmin** [comment]
I'm not completely sure but I do believe that Fedora uses /usr/sbin/modprobe by default. Which distribution have you tested LKRG on? RHEL or CentOS Stream?

**Comment by Krish-sysadmin** [comment]
Also not directly connected to this issue, but how would one use lkrg on Fedora such that on new kernel upgrades the module is built automatically using dkms? Might be easy to do but I don't know enough about dkms to know how. Thanks

**Comment by Krish-sysadmin** [comment]
Also not directly connected to this issue, but how would one use lkrg on Fedora such that on new kernel upgrades the module is built automatically using dkms? Might be easy to do but I don't know enough about dkms to know how. Thanks @solardiz

**Comment by solardiz** [comment]
@Krish-sysadmin We test on many different distributions - including automated testing here on GitHub Actions using different versions of Ubuntu, different kernels on those, and RHEL 7 and 8 rebuilds, and CentOS Stream 9. We do not have Fedora among automated tests, but we sometimes happen to try LKRG on different versions of Fedora as well.

Does the fix I committed earlier today work for you on Fedora 36? If it does, then please try reverting your lockdown setting to Fedora's default - it will probably work as well. Please let us know of your results of all of these tests. Thank you!

Regarding DKMS, that's off-topic on this issue, but I don't mind if someone more familiar with it and/or having tested it specifically with LKRG on Fedora answers.

**Comment by Krish-sysadmin** [comment]
> Does the fix I committed earlier today work for you on Fedora 36? If it does, then please try reverting your lockdown setting to Fedora's default - it will probably work as well. Please let us know of your results of all of these tests. Thank you!

Yup it does fix it. Thanks a ton.

Regarding DKMS, I realise its off topic, but I'm curious how you use lkrg personally? How do you get it to work on kernel upgrades? Thanks again

**Comment by solardiz** [comment]
@Krish-sysadmin I rebuild LKRG manually.

**Comment by Krish-sysadmin** [comment]
Regarding 2, according to https://github.com/dell/dkms would a simple ``dkms ldtarball /path/to.lkrg/0.9.3.tar.gz`` work?

**Comment by solardiz** [comment]
@Krish-sysadmin In GitHub Actions, it's several versions of Ubuntu. In our manual testing, it's also CentOS 7 and Alma/Rocky Linux 8.

**Comment by solardiz** [comment]
Arch Linux in particular has LKRG packaged, so presumably it works there: https://aur.archlinux.org/packages/lkrg-dkms

Anyway, we'd appreciate it if you continue testing on your Fedora, including with its default lockdown setting.

**Comment by Krish-sysadmin** [comment]
Also Fedora is a good distribution, I just have to test lkrg with dkms in a virtual machine and I'll then try it on my main.

**Comment by Krish-sysadmin** [comment]
> Arch Linux in particular has LKRG packaged, so presumably it works there: https://aur.archlinux.org/packages/lkrg-dkms

Well yes, but that's not part of the official repositories. It's like a copr

**Comment by Krish-sysadmin** [comment]
> Arch Linux in particular has LKRG packaged, so presumably it works there: https://aur.archlinux.org/packages/lkrg-dkms

I tried it and like Arch but getting SELinux to work on it is a pain because there aren't as many policies included as with Fedora or RHEL

**Comment by Krish-sysadmin** [comment]
Pull request #200 @solardiz
