### ISSUE TITLE
/usr/src/linux does not exist by default on Fedora

### ISSUE THREAD

**Issue by Krish-sysadmin** [lkrg-org/lkrg#206]
Hi. After following the DKMS instructions I attempt to run https://github.com/lkrg-org/lkrg/blob/main/scripts/add-exports.sh but I see that it has a dependency on the /usr/src/linux directory existing but that's not the case on a fresh Fedora 36 install. So how would we modify this script for that?

$ tree /usr/src/
/usr/src/
├── debug
└── kernels

**Comment by solardiz** [comment]
Thanks for reporting.

What were you trying to do? What's your reason to use this script in the first place? Did you run into an issue that it works around, and what was that, and is that the only such issue? In other words, was the script both necessary and sufficient in your case? One of the reasons I ask is because we'd consider simply dropping the script from our tree.

As to the directory name, you can pass any directory name corresponding to your kernel source tree to that script (via `KDIR=...` on its command line), and you'd normally use that script only along with a custom kernel build perhaps not coming from your distro anyway.

**Comment by Krish-sysadmin** [comment]
For now I am using the default kernel from my distro, Fedora, but in the future yes I plan to have a custom kernel. In this case (a) would I need that script or (b) should it work without? Thanks!

**Comment by Krish-sysadmin** [comment]
And if needed with a custom kernel build could you explain why it is needed in that case and not when you're using the kernel package from your distro?

**Comment by solardiz** [comment]
I'm no lockdown expert, but per my re-reading of a private discussion thread we had in 2020, the lockdown mode that's default with Secure Boot should work in newer kernels, which I think means `integrity`, and it was mentioned that `confidentiality` restricts use of kprobes, so presumably won't work. In summary, `integrity` should work and `confidentiality` should not.

Also, I think your questions would be more appropriate in separate threads in a discussion forum on LKRG. We currently only have the lkrg-users mailing list, which became inactive lately, but we could revitalize it. Having questions added to unrelated GitHub issues is not ideal.

**Comment by Krish-sysadmin** [comment]
I understand. Thanks anyway. Have a great day!

**Comment by Krish-sysadmin** [comment]
Hi, didn't want to open a whole new github issue for this. So people who use LKRG might be using a custom kernel. One such config I set up is https://pastebin.mozilla.org/GmPMoXk1/raw - shows the diff between Fedora's 5.18.11 kernel config vs custom. I believe LKRG depends on kprobes etc so whatever I was aware it depended on I left enabled in the kernel config.

 Is there something in there I need to change back or should that config work? 

Thanks @solardiz

**Comment by solardiz** [comment]
@Krish-sysadmin I'm sorry, I'm not going to spend my time on this, and I would be unlikely to spot everything just by looking. Good luck!

**Comment by Krish-sysadmin** [comment]
Ok, thank you. I'll just test it out and let you know if it works @solardiz

**Comment by solardiz** [comment]
@Krish-sysadmin Yes, loading the module like that is the first test you'd do after building it.
