### ISSUE TITLE
mkosi: No such script: /usr/share/debootstrap/scripts/mantic

### ISSUE THREAD

**Issue by Adam-pi3** [lkrg-org/lkrg#276]
mkosi fails with the `No such script: /usr/share/debootstrap/scripts/mantic` message for mainline:
https://github.com/lkrg-org/lkrg/actions/runs/5246772309/jobs/9476038644?pr=275

@vt-alt @wladmis would you be able to take a look?

**Comment by vt-alt** [comment]
So this is `debootstrap` error:
```
E: No such script: /usr/share/debootstrap/scripts/mantic
```
`mantic` is the future Ubuntu release 23.10. Perhaps `debootstrap` cannot install it.
 `mantic`  codename is taken from description of Ubuntu's `mainline` kernel packages—and their install only works for the Ubuntu release that 's mentioned (so we cannot install `mantic` packages on `lunar` as a workaround).

I don't know cause or solution yet, but I found some additional info which may be related to it: https://bugs.launchpad.net/ubuntu/+source/debootstrap/+bug/2020530
From the first glance it appears to be Ubuntu/debootstrap bug or feature (with the `status: In Progress → Won't Fix`).

**Comment by Adam-pi3** [comment]
Thanks @vt-alt for taking a look at it. I think we should just wai, @solardiz  what do you think?

**Comment by vt-alt** [comment]
Looks like it's self-fixed.
> ![image](https://github.com/lkrg-org/lkrg/assets/36664211/cc80237f-4d08-4513-a970-f4937e1a7fc8)
