### ISSUE TITLE
CI: CentOS Stream 8: Failed to download metadata for repo 'appstream'

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#342]
https://github.com/lkrg-org/lkrg/actions/runs/9725918554/job/26843781182

```
Run dnf install -y kernel-devel kernel gcc make elfutils-libelf-devel
CentOS Stream 8 - AppStream                     132  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

I first saw this happen on a PR here a few days ago, and it hasn't resolved since. @vt-alt

**Comment by vt-alt** [comment]
Yes they [EOL](https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/)ed and seems to removing infrastructure.

Perhaps it's time to remove this build.

**Comment by solardiz** [comment]
Thanks @vt-alt. I don't mind removing this test, given that we also have AlmaLinux 8 and Rocky Linux 8.
