### ISSUE TITLE
CI: CentOS 7 EOL

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#344]
CentOS 7 has just been EOL'ed, and our CI job is failing:

```
Run yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
```

Several forks of CentOS 7 are now to be maintained, a free one is https://linux.web.cern.ch/centos7/els7/ - we should probably override the baseurl for the repo to use this one.

**Comment by solardiz** [comment]
CERN ELS7 repo is empty for now, but I was almost able to get this job to work by using CERN's mirror of the original CentOS 7 repos with (under my GitHub account):

```diff
+++ b/.github/workflows/builds.yml
@@ -9,7 +9,9 @@ jobs:
             matrix:
                 include:
                     - image: centos:7
-                      run: yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
+                      run: |
+                          sed -i 's,^mirrorlist,#,; s,^#baseurl=http://mirror\.centos\.org,baseurl=https://linuxsoft.cern.ch/cern/,' /etc/yum.repos.d/CentOS-Base.repo
+                          yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                     - image: almalinux:8
                       run: yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                     - image: rockylinux:8
```

This seems to have installed the required packages just fine, but then failed with:

```
Run actions/checkout@v3
/usr/bin/docker exec  52ff85d8f9c120a77233bc9dfd3a9d96f7cb70fbfd9d339dec7c62cffc2791c0 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)
```

Indeed, CentOS 7's glibc is older than (based on 2.17), but then how did this work so far? Our usage of `checkout@v3` isn't new. Has anything changed in what `checkout@v3` actually is at this very same time? Intentionally timed to be right after CentOS 7 EOL maybe? Or it could be something else entirely. At this point I'm confused, @vt-alt.

**Comment by solardiz** [comment]
Got exact same issue with:

```diff
+++ b/.github/workflows/builds.yml
@@ -9,7 +9,9 @@ jobs:
             matrix:
                 include:
                     - image: centos:7
-                      run: yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
+                      run: |
+                          sed -i 's,^mirrorlist=,#,; s,^#baseurl=http://mirror\.centos\.org/centos/$releasever,baseurl=https://vault.centos.org/7.9.2009,' /etc/yum.repos.d/CentOS-Base.repo
+                          yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                     - image: almalinux:8
                       run: yum install -y kernel-devel kernel gcc make elfutils-libelf-devel
                     - image: rockylinux:8
```

**Comment by vt-alt** [comment]
This seems to be known problem: https://github.com/actions/runner/issues/2906
Ppl have some workaround suggestions there but who knows how long they will work.
```
   env:
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
```

And it seem related to internal GA infrastructure changes (using "Node20 instead of Node16").
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> ... We plan to migrate all actions to run on Node20 by Spring 2024. ...
> To support this change, we will be removing the Action runner support for the following operating systems which do not have official support for Node20:
> – Red Hat Enterprise Linux 7
> – CentOS 7
> – Oracle Linux 7

**Comment by solardiz** [comment]
Thanks @vt-alt! I am experimenting with this now. I first tried these `env` settings only for the CentOS 7 build, and this seemed to be somehow partially recognized - [build (centos:7, node16, true, sed -i 's,^mirrorlist=,#,; s,^#baseurl=http://mirror\.centos\.org/...](https://github.com/solardiz/lkrg/actions/runs/9800918933/job/27063436089#logs) - so mentions `node16` in the title, but then uses `node20` and fails. Then I tried these for all workflows in that file, and this worked! So I'll push that to this repo now.

**Comment by solardiz** [comment]
Just to record this in here, before your comment I had also tried downgrading from `checkout@v3` to `checkout@v2`, but this didn't make a difference.

**Comment by vt-alt** [comment]
> Thanks @vt-alt! I am experimenting with this now. I first tried these `env` settings only for the CentOS 7 build, and this seemed to be somehow partially recognized

Yes, and I am not sure build matrix supports setting env the same way as a whole job spec.

**Comment by vt-alt** [comment]
BTW, if they stop supporting this in actions runner, we could still try to build using Docker directly as in [cross.yml](https://github.com/lkrg-org/lkrg/blob/main/.github/workflows/cross.yml).
