### ISSUE TITLE
CI: ALT Sisyphus failing

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#360]
https://github.com/solardiz/lkrg/actions/runs/12124977914/job/33803883053

```
E: Couldn't find package kernel-headers-modules-un-def
```
@vt-alt

**Comment by vt-alt** [comment]
Oh yeah, we deleted `un-def` kernel in favor of numerical kernels. I added `latest` pseudo-flavour but it turned out to wok not as I expected (bringing 6.6 instead of 6.12 due to ALT apt bugs). I thought I will invent something complicated to bring the latest kernel but I didn't get idea yet.
